% perceive_data_fields
%
% Enumerate data fields appearing in json export from Percept.
%
% Arguments:
%   plot type: character string specifying the type of desired fields,
%           can be empty, or one of 'info', or 'data', respectively,
%           referring to fields used in percept.m to populate the info
%           header, and to process some fields, respectively. If empty,
%           all fields get returned.
%
% Returns: a character vector of fields
%
% Created by: T.Sieger, 2021-03-12
%
function flds = perceive_data_fields(dataType)

    % list of (hopefully) all data fields appearing in fson export
    % TODO: please, add new fields once you encounter some, e.g.
    % GroupUsagePercentage does not appear in the Percept white paper,
    % but it can be found in json export files
    dataFields = {...
        %  field                            info    data
        %   name                            field?  field?
        {'AbnormalEnd',                     false,  false},...
        {'BatteryInformation',              true,   false},...
        {'BatteryReminder',                 false,  false},...
        {'BrainSenseLfp',                   false,  true },...
        {'BrainSenseSurvey',                false,  true },...
        {'BrainSenseTimeDomain',            false,  true },...
        {'CalibrationTests',                false,  true },...
        {'DiagnosticData',                  true,   true },...
        {'DeviceInformation',               true,   false},...
        {'EventSummary',                    true,   true },...
        {'FullyReadForSession',             false,  false},...
        {'FeatureInformationCode',          false,  false},...
        {'Groups',                          true,   false},...
        {'GroupHistory',                    false,  false},...
        {'GroupUsageInformation',           false,  false},...
        {'GroupUsagePercentage',            false,  false},...
        {'Impedance',                       true,   true },...
        {'IndefiniteStreaming',             false,  true },...
        {'LeadConfiguration',               true,   false},...
        {'LfpMontage',                      false,  false},...
        {'LfpMontageTimeDomain',            false,  true },...
        {'MostRecentInSessionSignalCheck',  false,  true },...
        {'PatientEvents',                   true,   true },...
        {'ProgrammerTimezone',              false,  false},...
        {'ProgrammerUtcOffset',             false,  false},...
        {'ProgrammerLocale',                false,  false},...
        {'ProgrammerVersion',               false,  false},...
        {'PatientInformation',              true,   false},...
        {'Stimulation',                     true,   false},...
        {'SenseChannelTests',               false,  false},...
        {'SessionDate',                     true,   false},...
        {'SessionEndDate',                  true,   false},...
        {'Thresholds',                      false,  false}};

    % 'info field's refer to fields used in percept.m to populate the info header to
    % 'data field's refer to fields used in percept.m to process some fields (plot signals etc.)

    % Feel free to update the boolean flags in order to process more fields.

    idx=[];
    if nargin>0
        if dataType=='info'
            for i=1:length(dataFields)
                if dataFields{i}{2}
                    idx=[idx i];
                end
            end
        elseif dataType=='data'
            for i=1:length(dataFields)
                if dataFields{i}{3}
                    idx=[idx i];
                end
            end
        else
            error(['dataType ''' dataType ''' unsupported']);
        end
    else
        idx=1:length(dataFields);
    end

    flds=cell(1,length(idx));
    for i=1:length(idx)
        flds{i}=dataFields{idx(i)}{1};
    end

end
