function perceive_localsettings_construction_mat()

% Define taskItems per institution
taskItems = containers.Map;

taskItems('Charite') = { ...
    'Rest','RestTap','RestTapCont','RestFace','FingerTap','FingerTapL','FingerTapR','Rota','UPDRS', ...
    'MovArtWalk','MovArtStand','MovArtHead','MovArtArms','MonRevDyt','FTGRampUpThres','FTGFastRamp125Hz', ...
    'FTG110Hz','FTGBilateral','FTG145Hz','MID','SMTS','MSST','DualTask','Sync1','Sync2','RestTapBlock', ...
    'RestTapMonoRev','RestTapMonoRevNoBreaks','RestMovBlock','RestMovMonoRev','RestMovMonoRevNoBreaks', ...
    'RestMonoRev','RestMonoRevNoBreaks','Entrainment','TASK1','TASK2','TASK3','TASK4','TASK5', ...
    'XXXXX'};
taskItems('Wuerzburg') = { ...
    'Rest','RestTap','RestTapCont','RestFace','FingerTap','FingerTapL','FingerTapR','Rota','UPDRS', ...
    'MovArtWalk','MovArtStand','MovArtHead','MovArtArms','MonRevDyt','FTGRampUpThres','FTGFastRamp125Hz', ...
    'FTG110Hz','FTGBilateral','FTG145Hz','MID','SMTS','MSST','DualTask','Sync1','Sync2','RestTapBlock', ...
    'RestTapMonoRev','RestTapMonoRevNoBreaks','RestMovBlock','RestMovMonoRev','RestMovMonoRevNoBreaks', ...
    'RestMonoRev','RestMonoRevNoBreaks','Entrainment','TASK1','TASK2','TASK3','TASK4','TASK5', ...
    'XXXXX'};
taskItems('Duesseldorf') = { ...
    'Rest','RestTap','RestTapCont','RestFace','FingerTap','FingerTapL','FingerTapR','Rota','UPDRS', ...
    'MovArtWalk','MovArtStand','MovArtHead','MovArtArms','MonRevDyt','FTGRampUpThres','FTGFastRamp125Hz', ...
    'FTG110Hz','FTGBilateral','FTG145Hz','MID','SMTS','MSST','DualTask','Sync1','Sync2','RestTapBlock', ...
    'RestTapMonoRev','RestTapMonoRevNoBreaks','RestMovBlock','RestMovMonoRev','RestMovMonoRevNoBreaks', ...
    'RestMonoRev','RestMonoRevNoBreaks','Entrainment','TASK1','TASK2','TASK3','TASK4','TASK5', ...
    'XXXXX'};
taskItems('Default') = { ...
    'Rest','RestTap','RestTapCont','RestFace','FingerTap','FingerTapL','FingerTapR','Rota','UPDRS', ...
    'MovArtWalk','MovArtStand','MovArtHead','MovArtArms','MonRevDyt','FTGRampUpThres','FTGFastRamp125Hz', ...
    'FTG110Hz','FTGBilateral','FTG145Hz','MID','SMTS','MSST','DualTask','Sync1','Sync2','RestTapBlock', ...
    'RestTapMonoRev','RestTapMonoRevNoBreaks','RestMovBlock','RestMovMonoRev','RestMovMonoRevNoBreaks', ...
    'RestMonoRev','RestMonoRevNoBreaks','Entrainment','TASK1','TASK2','TASK3','TASK4','TASK5', ...
    'XXXXX'};

% Define stimLabels per institution
stimItems = containers.Map;

stimItems('Charite') = { ...
    'StimOff','StimOnR','StimOnL','StimOnB','StimX', ...
    'BurstL','BurstR','BurstB', ...
    'StimOn1L','StimOn1aL','StimOn1bL','StimOn1cL', ...
    'StimOn2L','StimOn2aL','StimOn2bL','StimOn2cL', ...
    'StimOn1R','StimOn1aR','StimOn1bR','StimOn1cR', ...
    'StimOn2R','StimOn2aR','StimOn2bR','StimOn2cR'};

stimItems('Wuerzburg') = { ...
    'StimOff','StimOnR','StimOnL','StimOnB','StimX', ...
    'BurstL','BurstR','BurstB', ...
    'StimOn1L','StimOn1aL','StimOn1bL','StimOn1cL', ...
    'StimOn2L','StimOn2aL','StimOn2bL','StimOn2cL', ...
    'StimOn1R','StimOn1aR','StimOn1bR','StimOn1cR', ...
    'StimOn2R','StimOn2aR','StimOn2bR','StimOn2cR'};

stimItems('Duesseldorf') = { ...
    'StimOff','StimOnR','StimOnL','StimOnB','StimX', ...
    'BurstL','BurstR','BurstB', ...
    'StimOn1L','StimOn1aL','StimOn1bL','StimOn1cL', ...
    'StimOn2L','StimOn2aL','StimOn2bL','StimOn2cL', ...
    'StimOn1R','StimOn1aR','StimOn1bR','StimOn1cR', ...
    'StimOn2R','StimOn2aR','StimOn2bR','StimOn2cR'};

stimItems('Default') = { ...
    'StimOff','StimOnR','StimOnL','StimOnB','StimX', ...
    'BurstL','BurstR','BurstB', ...
    'StimOn1L','StimOn1aL','StimOn1bL','StimOn1cL', ...
    'StimOn2L','StimOn2aL','StimOn2bL','StimOn2cL', ...
    'StimOn1R','StimOn1aR','StimOn1bR','StimOn1cR', ...
    'StimOn2R','StimOn2aR','StimOn2bR','StimOn2cR'};

% Charité-specific settings
check_followup_time = containers.Map;
check_followup_time('Charite')     = true;
check_followup_time('Wuerzburg')   = false;
check_followup_time('Duesseldorf') = false;
check_followup_time('Default')     = false;

check_gui_tasks = containers.Map;
check_gui_tasks('Charite')     = true;
check_gui_tasks('Wuerzburg')   = false;
check_gui_tasks('Duesseldorf') = false;
check_gui_tasks('Default')     = false;

check_gui_med = containers.Map;
check_gui_med('Charite')     = true;
check_gui_med('Wuerzburg')   = false;
check_gui_med('Duesseldorf') = false;
check_gui_med('Default')     = false;

convert2bids = containers.Map;
convert2bids('Charite')     = true;
convert2bids('Wuerzburg')   = false;
convert2bids('Duesseldorf') = false;
convert2bids('Default')     = false;

% Define datafields per institution
datafields = containers.Map;

% Charité-specific fields
datafields('Charite') = { ...
    'IndefiniteStreaming','LfpMontageTimeDomain'}; 
% If you want only DataVersion 1.2 specific fields for Charité:
% datafields('Charite') = sort({'BrainSenseSurveysTimeDomain','BrainSenseSurveys'});

% Würzburg-specific fields
datafields('Wuerzburg') = { ...
    'BrainSenseTimeDomain','BrainSenseSurveys','CalibrationTests','PatientEvents','DiagnosticData'};

% Düsseldorf-specific fields
datafields('Duesseldorf') = { ...
    'EventSummary','Impedance','MostRecentInSessionSignalCheck','BrainSenseLfp','BrainSenseTimeDomain', ...
    'IndefiniteStreaming','BrainSenseSurvey','BrainSenseSurveysTimeDomain','BrainSenseSurveys'};

% Default fields
datafields('Default') = { ...
    'EventSummary','Impedance','MostRecentInSessionSignalCheck','BrainSenseLfp','BrainSenseTimeDomain', ...
    'LfpMontageTimeDomain','IndefiniteStreaming','BrainSenseSurvey','CalibrationTests','PatientEvents', ...
    'DiagnosticData','BrainSenseSurveysTimeDomain','BrainSenseSurveys'};


% Toolbox root = directory containing perceive.m; write localsettings.mat under config/
toolboxDir = fileparts(which('perceive'));
if isempty(toolboxDir)
    error('Function perceive must be on the MATLAB path to locate toolbox/config/localsettings.mat.');
end
configPath = fullfile(toolboxDir, 'config', 'localsettings.mat');

% Save all maps into one file
save(configPath, ...
    'taskItems','stimItems','check_followup_time','check_gui_tasks','check_gui_med','convert2bids','datafields');

end