name: Run MATLAB Script
on: [push]
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024a
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: results = runtests('testAddNumbers'), assertSuccess(results);
      - name: Run MATLAB Tests
      uses: matlab-actions/run-tests@v2
      with:
        source: tests
